### ISSUE TITLE
LMAOOO

### ISSUE THREAD

**Issue by jojo989** [adddi0000/One-Click-Image-Logger#5]
bro its a fucking pyinstaller virus 💀 💀 💀 💀

**Comment by jojo989** [comment]
> 

ik but 💀

**Comment by Antsbatscats** [comment]
> btw i executed it, do you have my info?? just curious lol

Why would u ever execute it........... Here's some actual 'stuff' u can use: https://github.com/Antsbatscats/HarBringer

**Comment by Antsbatscats** [comment]
or its still here
