### ISSUE TITLE
you buggin out 💀

### ISSUE THREAD

**Issue by pampchog** [adddi0000/One-Click-Image-Logger#6]

**Comment by pampchog** [comment]
image logger with browser stealing and startup persistance is crazy 💀

people will probably fall for this since you created empyrean aswell

kids, image logging isnt real. dont run this lmfao

**Comment by pampchog** [comment]
I JUST REALISED THIS ISNT EVEN THE REAL ADDIDIX LMAOOOO

go to https://github.com/addi00000 instead, thats the real one

**Comment by jojo989** [comment]
HAHAHA
